aliases:
  - &install_dependencies
    name: Install dependencies
    command: |
      npm install
  - &restore_cache
    key : dependency-cache-{{ checksum "package.json" }}
  - &save_cache
    key: dependency-cache-{{ checksum "package.json" }}
    paths:
      - ./node_modules

defaults: &defaults
  docker:
    - image: circleci/node:lts

version: 2
jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: *install_dependencies
      - save_cache: *save_cache
      - run: npm run lint

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: *install_dependencies
      - save_cache: *save_cache
      - run: npm run build

workflows:
  version: 2
  ci:
    jobs:
      - lint
      - build
