import { Link } from 'gatsby';
import PropTypes from 'prop-types';
import React from 'react';
import Icon, { ICONS } from '../common/Icon';
import styles from './Header.module.scss';

export default class MenuItem extends React.Component {
  static propTypes = {
    id: PropTypes.string.isRequired,
    title: PropTypes.string.isRequired,
    path: PropTypes.string,
    menuItems: PropTypes.arrayOf(PropTypes.shape(MenuItem.propTypes)),
  };

  static defaultProps = {
    path: null,
    menuItems: [],
  };

  constructor() {
    super();
    this.state = {
      active: false,
    };
  }

  hasChild() {
    const { menuItems } = this.props;
    return Array.isArray(menuItems) && menuItems.length > 0;
  }
  render() {
    const { title, path, menuItems } = this.props;

    return (
      <li
        onMouseEnter={() => this.setState({ active: true })}
        onMouseLeave={() => this.setState({ active: false })}
        className={this.state.active ? styles.navActive : null}
      >
        {!this.hasChild() && <Link to={`${path}`}>{title}</Link>}

        {/* We use CSS to hide children. We can't rely on mouseover and state here because we want the html to be generated by gatsby for SEO purpose */}
        {this.hasChild() && (
          <>
            <span
              onTouchEnd={event => {
                this.setState(previousState => ({ active: !previousState.active }));
                event.preventDefault();
              }}
            >
              {title}
              <Icon icon={this.state.active ? ICONS.CHEVRON_UP : ICONS.CHEVRON_DOWN} />
            </span>
            <div>
              <ul>
                {menuItems.map(menuItem => (
                  <MenuItem key={menuItem.id} {...menuItem} />
                ))}
              </ul>
            </div>
          </>
        )}
      </li>
    );
  }
}
