import { Link } from 'gatsby';
import Icon, { ICONS } from '../components/Icon';
import React from 'react';
import styles from './Header.module.scss';

export default class MenuItem extends React.Component {
  constructor() {
    super();
    this.hasChildMenuItemClick = this.hasChildMenuItemClick.bind(this);
    this.state = {
      active: false,
    };
  }

  hasChild() {
    return Array.isArray(this.props.menuItems) && this.props.menuItems.length > 0;
  }
  hasChildMenuItemClick(e) {
    e.preventDefault();
    this.setState(previousState => ({ active: !previousState.active }));
  }
  render() {
    return (
      <li
        onMouseEnter={() => this.setState({ active: true })}
        onMouseLeave={() => this.setState({ active: false })}
        className={this.state.active ? styles.navActive : null}
      >
        <Link to={`${this.props.path}#${this.props.id}`} onClick={this.hasChildMenuItemClick}>
          {this.props.value}
          {this.hasChild() && (
            <Icon icon={this.state.active ? ICONS.CHEVRON_UP : ICONS.CHEVRON_DOWN} />
          )}
        </Link>
        {/* We use CSS to hide children. We can't rely on mouseover and state here because we want the html to be generated by gatsby for SEO purpose */}
        {this.hasChild() && (
          <div>
            <ul>
              {this.props.menuItems.map(menuItem => (
                <MenuItem key={menuItem.id} {...menuItem} />
              ))}
            </ul>
          </div>
        )}
      </li>
    );
  }
}
